function [cellidout] = DBget_cells_sortrange(conn,sortrange)
%[cellidout] = DBget_cells_sortrange(conn,sortrange)

query = ['SELECT DISTINCT cell.cellid '...
    ' FROM spiketrain '...
    ' JOIN cell ON cell.cellid = spiketrain.cellid ' ...
    ' JOIN sort ON sort.sortid = spiketrain.sortid ' ...
    ' WHERE sort.sortquality BETWEEN ' DBtool_num2strNULL(sortrange(1)) ' AND ' DBtool_num2strNULL(sortrange(2)) ...
    ' ORDER BY cell.cellid '];

cellidout = cell2mat(DBget_x(conn, query));

end