function [cellid] = DBget_cell_subject(conn, subjectid)
%[cellid] = DBget_cell_subject(conn, subjectid)

if length(subjectid) ~= 1
   error('one subject at a time, please'); 
end

query = ['SELECT cell.cellid ' ...
    ' FROM cell ' ...
    ' JOIN site ON site.siteid = cell.siteid ' ...
    ' JOIN penetration ON penetration.penetrationid = site.penetrationid ' ...
    ' JOIN subject ON subject.subjectid = penetration.subjectid ' ...
    ' WHERE subject.subjectid IN ' DBtool_inlist(subjectid)...
    ' ORDER BY cell.cellid'];

cellid = c2m(DBx(conn,query));

end